project:
  type: website

website:
  description: "Welcome to nakmuaycoder r&d-lab"
  site-url: https://nakmuaycoder.github.io/nakmuaycoder-r-d-lab/
  title: "My R&D Lab"
  open-graph: true
  twitter-card: true
  
  navbar:
    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/nakmuaycoder
      - icon: linkedin
        href: https://fr.linkedin.com/in/olivier-feher-%E0%B9%80%E0%B8%9F%E0%B9%81%E0%B8%AD%E0%B8%A3%E0%B9%8C-%E0%B9%82%E0%B8%AD%E0%B8%A5%E0%B8%B4%E0%B9%80%E0%B8%A7%E0%B8%B5%E0%B8%A2%E0%B8%A3%E0%B9%8C-9446b5105/en
      - icon: rss
        href: index.xml
        text: RSS

    left:
      - href: posts/index.qmd
        text: "Posts"
     
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true